spring:
  application:
    name: back-gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}


jwt:
  secret:
    key: ${JWT_SECRET}

server:
  port: 8081
  chatbot-url: ${CHATBOT_URL}
