version: '3.0'
services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    environment:
      TZ: "Asia/Seoul"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  spring:
    container_name: spring
    restart: always
    image: capstone30/spring
    env_file:
      - .env
    environment:
      TZ : "Asia/Seoul"
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy

  ruby:
    container_name: ruby
    restart: always
    image: capstone30/ruby
    env_file:
      - .env
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3000:3000"
    command: [ "bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0" ]

  nginx:
    container_name: nginx
    image: capstone30/nginx
    restart: unless-stopped
    environment:
      TZ: "Asia/Seoul"
    ports:
        - "80:80"
    depends_on:
      - "redis"
      - "spring"
      - "ruby"

