name: Deploy Server

on:
  push:
    branches:
      - develop-back
      - main
      - feautre/be/#134-ApiGateway
permissions:
  contents: read

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create env file
        run: |
          pwd
          echo DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} >> .env
          echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo JWT_ACCESS_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_EXPIRATION_TIME }} >> .env
          echo JWT_REFRESH_EXPIRATION_TIME=${{ secrets.JWT_REFRESH_EXPIRATION_TIME }} >> .env
          echo HMAC_SECRET=${{ secrets.HMAC_SECRET }} >> .env
          echo HMAC_ALGORITHM=${{ secrets.HMAC_ALGORITHM }} >> .env
          echo DeepL_API_KEY=${{ secrets.DeepL_API_KEY }} >> .env
          echo TEST_KEY=${{ secrets.TEST_KEY }} >> .env
          echo Azure_API_KEY=${{ secrets.Azure_API_KEY }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} >> .env
          echo S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} >> .env
          echo SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} >> .env
          echo SERVER_NAME=${{ secrets.SERVER_NAME }} >> .env
          echo SERVER_URL=${{ secrets.SERVER_URL }} >> .env
          echo CHATBOT_URL=${{ secrets.CHATBOT_URL }} >> .env
          ls -a

      - name: Copy .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          source: "./.env"
          target: "capstone"

      - name: Copy docker-compose.yaml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          source: "./back/docker-compose.yml"
          target: "capstone"